// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: prc10/prc10.proto

package prc10

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_oracleNetworkProtocol_plugchain_sdk_go_types "github.com/oracleNetworkProtocol/plugchain-sdk-go/types"
	types "github.com/oracleNetworkProtocol/plugchain-sdk-go/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Token defines a standard for the fungible token
type Token struct {
	Symbol        string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scale         uint32 `protobuf:"varint,3,opt,name=scale,proto3" json:"scale,omitempty"`
	MinUnit       string `protobuf:"bytes,4,opt,name=min_unit,json=minUnit,proto3" json:"min_unit,omitempty" yaml:"min_unit"`
	InitialSupply uint64 `protobuf:"varint,5,opt,name=initial_supply,json=initialSupply,proto3" json:"initial_supply,omitempty" yaml:"initial_supply"`
	MaxSupply     uint64 `protobuf:"varint,6,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty" yaml:"max_supply"`
	Mintable      bool   `protobuf:"varint,7,opt,name=mintable,proto3" json:"mintable,omitempty"`
	Owner         string `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *Token) Reset()      { *m = Token{} }
func (*Token) ProtoMessage() {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6719b2535041a49, []int{0}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Token.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return m.Size()
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

// token parameters
type Params struct {
	IssueTokenBaseFee    types.Coin                                                  `protobuf:"bytes,1,opt,name=issue_token_base_fee,json=issueTokenBaseFee,proto3" json:"issue_token_base_fee"`
	OperateTokenFeeRatio github_com_oracleNetworkProtocol_plugchain_sdk_go_types.Dec `protobuf:"bytes,2,opt,name=operate_token_fee_ratio,json=operateTokenFeeRatio,proto3,customtype=github.com/oracleNetworkProtocol/plugchain-sdk-go/types.Dec" json:"operate_token_fee_ratio"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6719b2535041a49, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Token)(nil), "plugchain.prc10.Token")
	proto.RegisterType((*Params)(nil), "plugchain.prc10.Params")
}

func init() { proto.RegisterFile("prc10/prc10.proto", fileDescriptor_c6719b2535041a49) }

var fileDescriptor_c6719b2535041a49 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xb1, 0x6e, 0xd3, 0x50,
	0x14, 0xb5, 0x4b, 0x92, 0xa6, 0x0f, 0x95, 0x2a, 0x26, 0x05, 0x37, 0x83, 0x1d, 0x79, 0xca, 0x52,
	0x9b, 0x00, 0x53, 0x18, 0x40, 0x2e, 0xea, 0x88, 0x22, 0x03, 0x0b, 0x12, 0xb2, 0x9e, 0xdd, 0xdb,
	0xf4, 0x29, 0x7e, 0xbe, 0x96, 0xdf, 0x33, 0x6d, 0xf8, 0x02, 0x46, 0x46, 0xc6, 0xfc, 0x00, 0xff,
	0x91, 0xb1, 0x23, 0x62, 0x88, 0x4a, 0xb2, 0x30, 0xe7, 0x0b, 0x90, 0x9f, 0x9d, 0x48, 0x8c, 0x5d,
	0xac, 0x7b, 0xce, 0xf5, 0xf1, 0xf1, 0x3d, 0xf7, 0x92, 0x4e, 0x96, 0xc7, 0xc3, 0x67, 0x9e, 0x7a,
	0xba, 0x59, 0x8e, 0x12, 0x8d, 0xa3, 0x2c, 0x29, 0x26, 0xf1, 0x15, 0x65, 0xa9, 0xab, 0xe8, 0x9e,
	0x15, 0xa3, 0xe0, 0x28, 0xbc, 0x88, 0x0a, 0xf0, 0xbe, 0x0c, 0x23, 0x90, 0x74, 0xe8, 0xc5, 0xa8,
	0xfa, 0x28, 0xb1, 0xd7, 0x9d, 0xe0, 0x04, 0x55, 0xe9, 0x95, 0x55, 0xc5, 0x3a, 0x3f, 0xf7, 0x48,
	0xf3, 0x03, 0x4e, 0x21, 0x35, 0x9e, 0x90, 0x96, 0x98, 0xf1, 0x08, 0x13, 0x53, 0xef, 0xeb, 0x83,
	0x83, 0xa0, 0x46, 0x86, 0x41, 0x1a, 0x29, 0xe5, 0x60, 0xee, 0x29, 0x56, 0xd5, 0x46, 0x97, 0x34,
	0x45, 0x4c, 0x13, 0x30, 0x1f, 0xf4, 0xf5, 0xc1, 0x61, 0x50, 0x01, 0xc3, 0x25, 0x6d, 0xce, 0xd2,
	0xb0, 0x48, 0x99, 0x34, 0x1b, 0xe5, 0xdb, 0xfe, 0xe3, 0xcd, 0xd2, 0x3e, 0x9a, 0x51, 0x9e, 0x8c,
	0x9c, 0x6d, 0xc7, 0x09, 0xf6, 0x39, 0x4b, 0x3f, 0xa6, 0x4c, 0x1a, 0x6f, 0xc8, 0x23, 0x96, 0x32,
	0xc9, 0x68, 0x12, 0x8a, 0x22, 0xcb, 0x92, 0x99, 0xd9, 0xec, 0xeb, 0x83, 0x86, 0x7f, 0xb2, 0x59,
	0xda, 0xc7, 0x95, 0xea, 0xff, 0xbe, 0x13, 0x1c, 0xd6, 0xc4, 0x7b, 0x85, 0x8d, 0x97, 0x84, 0x70,
	0x7a, 0xb3, 0x55, 0xb7, 0x94, 0xfa, 0x78, 0xb3, 0xb4, 0x3b, 0xb5, 0xe7, 0xae, 0xe7, 0x04, 0x07,
	0x9c, 0xde, 0xd4, 0xaa, 0x9e, 0xfa, 0x4f, 0x49, 0xa3, 0x04, 0xcc, 0xfd, 0xbe, 0x3e, 0x68, 0x07,
	0x3b, 0x5c, 0x4e, 0x86, 0xd7, 0x29, 0xe4, 0x66, 0x5b, 0x8d, 0x5b, 0x81, 0x51, 0xfb, 0xdb, 0xdc,
	0xd6, 0x7e, 0xcc, 0x6d, 0xcd, 0xb9, 0xd3, 0x49, 0x6b, 0x4c, 0x73, 0xca, 0x85, 0x31, 0x26, 0x5d,
	0x26, 0x44, 0x01, 0xa1, 0x2c, 0xf3, 0x0b, 0xcb, 0xdc, 0xc3, 0x4b, 0x00, 0x15, 0xdf, 0xc3, 0xe7,
	0x27, 0x6e, 0xb5, 0x0f, 0xb7, 0xe4, 0xdd, 0x7a, 0x1f, 0xee, 0x19, 0xb2, 0xd4, 0x6f, 0x2c, 0x96,
	0xb6, 0x16, 0x74, 0x94, 0x58, 0x65, 0xef, 0x53, 0x01, 0xe7, 0x00, 0xc6, 0x57, 0xf2, 0x14, 0x33,
	0xc8, 0xa9, 0xdc, 0x7e, 0xf3, 0x12, 0x20, 0xcc, 0xa9, 0x64, 0x58, 0xa5, 0xef, 0x9f, 0x95, 0xca,
	0xdf, 0x4b, 0xfb, 0xd5, 0x84, 0xc9, 0xab, 0x22, 0x72, 0x63, 0xe4, 0x1e, 0xe6, 0x34, 0x4e, 0xe0,
	0x1d, 0xc8, 0x6b, 0xcc, 0xa7, 0xe3, 0x72, 0xa9, 0x31, 0x26, 0xde, 0xee, 0x3a, 0x4e, 0xc5, 0xc5,
	0xf4, 0x74, 0x82, 0x9e, 0x9c, 0x65, 0x20, 0xdc, 0xb7, 0x10, 0x07, 0xdd, 0xda, 0x43, 0x59, 0x9f,
	0x03, 0x04, 0xa5, 0xc1, 0xa8, 0x5d, 0x8e, 0xf7, 0x77, 0x6e, 0xeb, 0xfe, 0xe7, 0xc5, 0x1f, 0x4b,
	0x5b, 0xac, 0x2c, 0xfd, 0x76, 0x65, 0xe9, 0x77, 0x2b, 0x4b, 0xff, 0xbe, 0xb6, 0xb4, 0xdb, 0xb5,
	0xa5, 0xfd, 0x5a, 0x5b, 0xda, 0xa7, 0xd7, 0xf7, 0xb7, 0xe6, 0x78, 0x51, 0x24, 0x20, 0xaa, 0xf3,
	0x8d, 0x5a, 0xea, 0xf0, 0x5e, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x76, 0x9f, 0x61, 0xc6, 0xd4,
	0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.IssueTokenBaseFee.Equal(&that1.IssueTokenBaseFee) {
		return false
	}
	if !this.OperateTokenFeeRatio.Equal(that1.OperateTokenFeeRatio) {
		return false
	}
	return true
}
func (m *Token) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Token) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Token) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintPrc10(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x42
	}
	if m.Mintable {
		i--
		if m.Mintable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.MaxSupply != 0 {
		i = encodeVarintPrc10(dAtA, i, uint64(m.MaxSupply))
		i--
		dAtA[i] = 0x30
	}
	if m.InitialSupply != 0 {
		i = encodeVarintPrc10(dAtA, i, uint64(m.InitialSupply))
		i--
		dAtA[i] = 0x28
	}
	if len(m.MinUnit) > 0 {
		i -= len(m.MinUnit)
		copy(dAtA[i:], m.MinUnit)
		i = encodeVarintPrc10(dAtA, i, uint64(len(m.MinUnit)))
		i--
		dAtA[i] = 0x22
	}
	if m.Scale != 0 {
		i = encodeVarintPrc10(dAtA, i, uint64(m.Scale))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintPrc10(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintPrc10(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.OperateTokenFeeRatio.Size()
		i -= size
		if _, err := m.OperateTokenFeeRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPrc10(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.IssueTokenBaseFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPrc10(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintPrc10(dAtA []byte, offset int, v uint64) int {
	offset -= sovPrc10(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Token) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovPrc10(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPrc10(uint64(l))
	}
	if m.Scale != 0 {
		n += 1 + sovPrc10(uint64(m.Scale))
	}
	l = len(m.MinUnit)
	if l > 0 {
		n += 1 + l + sovPrc10(uint64(l))
	}
	if m.InitialSupply != 0 {
		n += 1 + sovPrc10(uint64(m.InitialSupply))
	}
	if m.MaxSupply != 0 {
		n += 1 + sovPrc10(uint64(m.MaxSupply))
	}
	if m.Mintable {
		n += 2
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovPrc10(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.IssueTokenBaseFee.Size()
	n += 1 + l + sovPrc10(uint64(l))
	l = m.OperateTokenFeeRatio.Size()
	n += 1 + l + sovPrc10(uint64(l))
	return n
}

func sovPrc10(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPrc10(x uint64) (n int) {
	return sovPrc10(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Token) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPrc10
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Token: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Token: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrc10
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPrc10
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPrc10
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrc10
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPrc10
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPrc10
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scale", wireType)
			}
			m.Scale = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrc10
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Scale |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinUnit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrc10
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPrc10
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPrc10
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinUnit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialSupply", wireType)
			}
			m.InitialSupply = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrc10
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitialSupply |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSupply", wireType)
			}
			m.MaxSupply = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrc10
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSupply |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mintable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrc10
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Mintable = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrc10
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPrc10
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPrc10
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPrc10(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPrc10
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPrc10
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssueTokenBaseFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrc10
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPrc10
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPrc10
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.IssueTokenBaseFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperateTokenFeeRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPrc10
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPrc10
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPrc10
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OperateTokenFeeRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPrc10(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPrc10
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPrc10(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPrc10
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPrc10
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPrc10
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPrc10
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPrc10
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPrc10
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPrc10        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPrc10          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPrc10 = fmt.Errorf("proto: unexpected end of group")
)
